export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_COURSES = 'GET_COURSES';
export const GET_COURSE = 'GET_COURSE';
export const GET_COURSES_CATEGORY = 'GET_COURSES_CATEGORY';
export const GET_NUMBER_OF_COURSES = 'GET_NUMBER_OF_COURSES';
export const GET_USERS = 'GET_USERS';
export const COURSE_LOADING = 'COURSE_LOADING';
export const USER_LOADING = 'USER_LOADING';
export const INQ_LOADING = 'INQ_LOADING';
export const LOGOUT = 'LOGOUT';
export const GET_NUMBER_OF_USERS = 'GET_NUMBERS_OF_USERS';
export const GET_NUMBER_OF_REGISTERED_COURESES =
  'GET_NUMBER_OF_REGISTERED_COURESES';
export const GET_NUMBER_OF_USERS_WHOSE_REGISTERED_COURSES =
  'GET_NUMBER_OF_USERS_WHOSE_REGISTERED_COURSES';
export const CURRENT_PROFILE = 'CURRENT_PROFILE';
export const GET_REGISTERED_COURSES = 'GET_REGISTERED_COURSES';
export const GET_LAST_FIVE_USERS = 'GET_LAST_FIVE_USERS';
export const GET_INQUIRIES = 'GET_INQUIRIES';
export const GET_LAST_FIVE_REGISTERED_COURSES =
  'GET_LAST_FIVE_REGISTERED_COURSES';
